package de.uol.swp.client;

import de.uol.swp.client.game.GameObjects.TerrainField;
import de.uol.swp.client.game.HelperObjects.Vector;
import org.junit.jupiter.api.Test;

import static javafx.scene.paint.Color.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class TerrainFieldTest {

    TerrainField tf1 = new TerrainField(new Vector(4, 2));
    TerrainField tf2 = new TerrainField(new Vector(4, 2));
    TerrainField tf3 = new TerrainField(new Vector(4, 2));
    TerrainField tf4 = new TerrainField(new Vector(4, 2));
    TerrainField tf5 = new TerrainField(new Vector(4, 2));
    TerrainField tf6 = new TerrainField(new Vector(4, 2));
    TerrainField tf7 = new TerrainField(new Vector(4, 2));
    TerrainField tf8 = new TerrainField(new Vector(4, 2));


    /**
     * This test checks, if the correct color is generated by TerrainField.name .
     * <p>
     * The color of the Terrainfield is not hardcoded into the class, but determined by a switch-case statement. This
     * way, just one variable needs to be changed instead of every TerrainField in the Array.
     * </p>
     *
     * @author Pieter Vogt
     * @since 2021-03-10
     */

    @Test
    void testColorDetermination() {
        tf1.setName("Farmland");
        tf2.setName("Grassland");
        tf3.setName("Hillside");
        tf4.setName("Mountain");
        tf5.setName("Ocean");
        tf6.setName("Mountain");
        tf7.setName("Desert");
        tf8.setName("Forest");
        assertEquals(GOLDENROD, tf1.determineColorOfTerrain());
        assertEquals(LAWNGREEN, tf2.determineColorOfTerrain());
        assertEquals(LIGHTCORAL, tf3.determineColorOfTerrain());
        assertEquals(GREY, tf4.determineColorOfTerrain());
        assertEquals(DODGERBLUE, tf5.determineColorOfTerrain());
        assertEquals(GREY, tf6.determineColorOfTerrain());
        assertEquals(BLANCHEDALMOND, tf7.determineColorOfTerrain());
        assertEquals(OLIVEDRAB, tf8.determineColorOfTerrain());
    }

}